# evtest-qt - A graphical joystick tester
# Copyright (C) 2015 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:18.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    build-essential
    git
    cmake
    g++-8
    g++-5
    clang-6.0
    libqt4-dev
    qtbase5-dev

.build_evtest_template: &build_evtest
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DUSE_QT5=$USE_QT5
    - make VERBOSE=1
    # - make test VERBOSE=1 ARGS="-V"

build:qt5:gcc5:release:
  <<: *build_evtest
  variables:
    CXX: "g++-5"
    USE_QT5: "ON"
    BUILD_TYPE: "Release"

build:qt5:gcc:release:
  <<: *build_evtest
  variables:
    CXX: "g++-8"
    USE_QT5: "ON"
    BUILD_TYPE: "Release"

build:qt5:clang:release:
  <<: *build_evtest
  variables:
    CXX: "clang++-6.0"
    USE_QT5: "ON"
    BUILD_TYPE: "Release"

build:qt5:gcc5:debug:
  <<: *build_evtest
  variables:
    CXX: "g++-5"
    USE_QT5: "ON"
    BUILD_TYPE: "Debug"

build:qt5:gcc:debug:
  <<: *build_evtest
  variables:
    CXX: "g++-8"
    USE_QT5: "ON"
    BUILD_TYPE: "Debug"

build:qt5:clang:debug:
  <<: *build_evtest
  variables:
    CXX: "clang++-6.0"
    USE_QT5: "ON"
    BUILD_TYPE: "Debug"

build:qt4:gcc5:release:
  <<: *build_evtest
  variables:
    CXX: "g++-5"
    USE_QT5: "OFF"
    BUILD_TYPE: "Release"

build:qt4:gcc:release:
  <<: *build_evtest
  variables:
    CXX: "g++-8"
    USE_QT5: "OFF"
    BUILD_TYPE: "Release"

build:qt4:clang:release:
  <<: *build_evtest
  variables:
    CXX: "clang++-6.0"
    USE_QT5: "OFF"
    BUILD_TYPE: "Release"

build:qt4:gcc5:debug:
  <<: *build_evtest
  variables:
    CXX: "g++-5"
    USE_QT5: "OFF"
    BUILD_TYPE: "Debug"

build:qt4:gcc:debug:
  <<: *build_evtest
  variables:
    CXX: "g++-8"
    USE_QT5: "OFF"
    BUILD_TYPE: "Debug"

build:qt4:clang:debug:
  <<: *build_evtest
  variables:
    CXX: "clang++-6.0"
    USE_QT5: "OFF"
    BUILD_TYPE: "Debug"

# EOF #
