#!/usr/bin/env python3


import re


def gen_event_list(rgx, outfilename):
    with open(outfilename, 'w') as fout:
        fout.write("// autogenerated by gen_event_list.rb, do not edit by hand\n\n")

        with open("/usr/include/linux/input.h", 'r') as fin:
            for line in [l for l in fin.readlines() if re.search(rgx, l)]:
                name = line.split()[1]
                if not re.search(r'(_MAX|_CNT)$', name):
                    fout.write("#ifdef {}\n".format(name))
                    fout.write("  add({}, \"{}\");\n".format(name, name))
                    fout.write("#endif\n\n")

        fout.write("/* EOF */\n")


if __name__ == "__main__":
    gen_event_list(r'^#define (BTN|KEY)', 'key_list.x')
    gen_event_list(r'^#define REL', 'rel_list.x')
    gen_event_list(r'^#define ABS', 'abs_list.x')


# EOF #
